spring:
  main:
    allow-circular-references: true
  application:
    name: business card
#  security:
#    user:
#      name: Mike
#      password: password

  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/business-card
    username: user
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: never
#       mode: always
##      при первой инициализации
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop